In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a*b)

[ 4 10 18]


### for with two variables

In [ ]:
c = [1,2,3]
d = [4,5,6]
for i,j in zip(c,d):
  print(i*j,end=" ")

4 10 18 

### Basics

In [ ]:
#initializing 2d numpy array
x = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[15,16,17,18,19,20,21]],dtype='int32')

In [ ]:
#get shape
print(x.shape)

(3, 7)


In [ ]:
#get number of dimensions
print(x.ndim)

2


In [ ]:
#get data type
x.dtype

dtype('int32')

In [ ]:
#turning a numpy array into a column vector
y = x
y=y.reshape(x.shape[0]*x.shape[1],1)
print(y.shape)
print(y)

(21, 1)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]]


In [ ]:
#initializing a numpy array with zeros
arr = np.zeros((5,5))#defining the dimensions
print(arr)

arr2 = np.zeros(10)#only one row
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
a = np.array([1,2,3,4,5,6])

In [ ]:
#size of item in bytes
a.itemsize

8

In [ ]:
#number of elements in an array
a.size

6

In [ ]:
#size of the whole array in bytes
print(a.size * a.itemsize)
print(a.nbytes)

48
48


### Accessing/changing specific elements, rows, columns, etc

In [ ]:
arry = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [ ]:
#get a specific element
print(arry[0,6])

7


In [ ]:
#a specific row
print(arry[1,:])

[ 8  9 10 11 12 13 14]


In [ ]:
#get a column
print(arry[:,0])

[1 8]


In [ ]:
#some fancy stuff
print(arry[1,1:-1:2])#the two at the end makes it step by two

[ 9 11 13]


In [ ]:
arry[0,6] = 33
print(arry)

[[ 1  2  3  4  5  6 33]
 [ 8  9 10 11 12 13 14]]


In [ ]:
arry[:,2] = 7
print(arry)

[[ 1  2  7  4  5  6 33]
 [ 8  9  7 11 12 13 14]]


In [ ]:
arry[0,0:3] = np.arange(3)#[0,1,2] would yeild the same result
print(arry)

[[ 0  1  2  4  5  6 33]
 [ 8  9  7 11 12 13 14]]


### initializing different types of arrays

In [ ]:
#with zeros
mtrx = np.zeros((2,3))
mtrx

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#with ones
mtrx2 = np.ones((3,3),dtype="int16")
print(mtrx2.itemsize)
print(mtrx2)

2
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#with a particular value
mtrx3 = np.full((3,4),18)#first we pass the shape "(3,4)" and then the value "18"
print(mtrx3)

[[18 18 18 18]
 [18 18 18 18]
 [18 18 18 18]]


In [ ]:
#same as the previous just using full_like
mtrx4 = np.full_like(mtrx3,18)
print(mtrx4)

[[18 18 18 18]
 [18 18 18 18]
 [18 18 18 18]]


In [ ]:
#a simple applicaation
arr = np.zeros((5,5))
arr[0,:] = arr[4,:] = 1 #filling the exterior rows with ones
arr[1:4,0] = arr[1:4,4] = 1 #filling the exterior columns with ones
arr[2,2] = 9
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### copying arrays

In [ ]:
#the following makes an array point to another array
a = np.array([1,2,3,4])
b = a
b[3] = 100
print(b)
print(a)

[  1   2   3 100]
[  1   2   3 100]


In [ ]:
#the following just copies the elemnts of one array into another
a = np.array([1,2,3,4])
b = a.copy()
b[3] = 100
print(b)
print(a)

[  1   2   3 100]
[1 2 3 4]


# Maths

### Basics

In [ ]:
x = np.array([1,2,3,4,5])

In [ ]:
x += 3
x

array([4, 5, 6, 7, 8])

In [ ]:
x -= 3
x

array([1, 2, 3, 4, 5])

In [ ]:
x *= 2
x

array([ 2,  4,  6,  8, 10])

In [ ]:
x = x/2 #can't use /= because numpy doesn't allow /= to chage from int to float if you wish to use it change the dtype upon declaration of the array
x

array([1., 2., 3., 4., 5.])

In [ ]:
x **= 2# ** is power
x

array([ 1.,  4.,  9., 16., 25.])

In [ ]:
print(np.sin(x))
print(np.cos(x))

[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]


### Linear Algebra

In [ ]:
a = np.ones((3,3))
print("a:")
print(a)
b = np.full((3,2),3)
print("b:")
print(b)
print("their matrix multiplication:")
print("first method")
print(np.dot(a,b))
print("second method")
print(np.matmul(a,b))

a:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
b:
[[3 3]
 [3 3]
 [3 3]]
their matrix multiplication:
first method
[[9. 9.]
 [9. 9.]
 [9. 9.]]
second method
[[9. 9.]
 [9. 9.]
 [9. 9.]]


In [ ]:
#finding the determinant
c = np.identity(3)#identity matrix
np.linalg.det(c)

1.0

In [ ]:
#the inverse of a matrix
np.linalg.inv(c)#the inverse of the identity matrix is itself

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Statistics

In [ ]:
stats = np.random.rand(3,3)
stats

array([[0.60158326, 0.30286141, 0.41136257],
       [0.01550084, 0.21388619, 0.25403942],
       [0.9351151 , 0.585175  , 0.58033378]])

In [ ]:
np.min(stats)

0.015500840078547018

In [ ]:
np.max(stats,axis=1)#max at each row

array([0.60158326, 0.25403942, 0.9351151 ])

In [ ]:
np.min(stats,axis=0)#min at each column

array([0.01550084, 0.21388619, 0.25403942])

In [ ]:
np.sum(stats)

3.8998575693940447

In [ ]:
#the average(mean)
np.mean(stats)

0.4333175077104494

## Reorganizing arrays

In [ ]:
orgnl = np.arange(15)
orgnl

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
modified = orgnl.reshape(3,5)
modified

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Deleting rows and columns

In [ ]:
f = np.arange(15).reshape(3,5)
print(f)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
#deleting rows
f_delr = np.delete(f,1,0)
#the second parameter is the index of the row or the column
#the last parameter specifies whether we're deleting from rows or colmuns if 0 it's rows if 1 it's columns

print(f_delr)

[[ 0  1  2  3  4]
 [10 11 12 13 14]]


In [ ]:
#deleting columns
f_delc = np.delete(f,3,1)#we are deleting the fourth column which has index 3 and the last parameter 1 specifies that it's a column
print(f_delc)

[[ 0  1  2  4]
 [ 5  6  7  9]
 [10 11 12 14]]


### stacking arrays

In [ ]:
#vertically
v1 = np.arange(4)
v2 = np.arange(4,8)
print("v1:",v1)
print("v2:",v2)
np.vstack([v1,v2])

v1: [0 1 2 3]
v2: [4 5 6 7]


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
#horizontally
h1 = np.random.randint(8,size=(2,4))
h2 = np.random.randint(2,11,size=(2,3))
print("h1:",h1)
print("h2:",h2)
np.hstack([h1,h2])

h1: [[3 2 3 4]
 [3 0 4 4]]
h2: [[7 8 4]
 [5 2 8]]


array([[3, 2, 3, 4, 7, 8, 4],
       [3, 0, 4, 4, 5, 2, 8]])